name: Iron Semi Binary Testing
on:
  workflow_dispatch:
    branches:
      - iron
  pull_request:
    branches:
      - iron
  push:
    branches:
      - iron
  schedule:
    - cron: '13 4 * * *'

jobs:
  binary:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: iron
      ros_repo: testing
      ref_for_scheduled_build: iron
      upstream_workspace: Universal_Robots_ROS2_Gazebo_Simulation.iron.repos
