name: Rolling Binary Testing
on:
  workflow_dispatch:
    branches:
      - ros2
  pull_request:
    branches:
      - ros2
  push:
    branches:
      - ros2
  schedule:
    - cron: '13 4 * * *'

jobs:
  binary:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: rolling
      ros_repo: testing
      ref_for_scheduled_build: ros2
